# Generated by Django 5.1.4 on 2024-12-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('creation_tms', models.DateTimeField(editable=False)),
                ('last_update_tms', models.DateTimeField()),
            ],
        ),
    ]
