# Generated by Django 5.1.4 on 2024-12-25 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('creation_tms', models.DateTimeField(default=datetime.datetime(2024, 12, 26, 0, 24, 57, 538593), editable=False)),
                ('last_update_tms', models.DateTimeField(default=datetime.datetime(2024, 12, 26, 0, 24, 57, 538622))),
            ],
        ),
    ]
