# Generated by Django 5.1.4 on 2024-12-11 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('creation_tms', models.DateTimeField(default=datetime.datetime(2024, 12, 12, 1, 23, 46, 141464), editable=False)),
                ('last_update_tms', models.DateTimeField(default=datetime.datetime(2024, 12, 12, 1, 23, 46, 141464))),
            ],
        ),
    ]
